"""
generate_drafts.py — CLI entry point for the IT Simplification Communications Engine.

Responsibility:
    Orchestrate the full pipeline (ingest → engine → output) and render the
    structured weekly update into a single human-readable Markdown file.

Usage:
    python scripts/generate_drafts.py --input "data/Fake vendor data.xlsx"
    python scripts/generate_drafts.py --input "data/Fake vendor data.xlsx" --output output/drafts.md
"""

import argparse
import sys
from datetime import date
from pathlib import Path

# Ensure the scripts directory is on the path so sibling modules are importable.
sys.path.insert(0, str(Path(__file__).resolve().parent))

from ingest import load_vendor_data
from communications_engine import generate_weekly_update, WeeklyUpdate


def render_markdown(update: WeeklyUpdate) -> str:
    """Render a WeeklyUpdate dataclass into a Markdown document."""
    lines: list[str] = []

    # Header
    lines.append("# IT Simplification — Weekly Update")
    lines.append(f"Generated: {date.today().isoformat()}")
    lines.append("")

    # Executive Summary
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(update.executive_summary)
    lines.append("")

    # Key Metrics
    lines.append("## Key Metrics")
    lines.append("")
    m = update.metrics
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Total savings identified | ${m['total_savings_identified']:,.0f} |")
    lines.append(f"| Finalised savings | ${m['finalised_savings']:,.0f} |")
    lines.append(f"| Savings pipeline | ${m['savings_pipeline']:,.0f} |")
    lines.append(f"| Total budget | ${m['total_budget']:,.0f} |")
    lines.append(f"| Total renewal price | ${m['total_renewal_price']:,.0f} |")
    lines.append(f"| Vendors in scope | {m['vendor_count']} |")
    lines.append("")

    # Highlights
    lines.append("## Highlights")
    lines.append("")
    for item in update.highlights:
        lines.append(f"- {item}")
    if not update.highlights:
        lines.append("- No highlights this period.")
    lines.append("")

    # Risks
    lines.append("## Risks")
    lines.append("")
    for item in update.risks:
        lines.append(f"- {item}")
    lines.append("")

    # Next Steps
    lines.append("## Next Steps")
    lines.append("")
    for item in update.next_steps:
        lines.append(f"- {item}")
    lines.append("")

    # Footer
    lines.append("---")
    lines.append("*End of update. Generated by IT Simplification Communications Engine.*")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a weekly IT Simplification update from vendor data."
    )
    parser.add_argument(
        "--input",
        required=True,
        help="Path to the .xlsx file containing vendor data.",
    )
    parser.add_argument(
        "--output",
        default="output/drafts.md",
        help="Path for the generated Markdown draft (default: output/drafts.md).",
    )

    args = parser.parse_args()

    # --- Ingest ---
    try:
        df = load_vendor_data(args.input)
    except FileNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except ValueError as e:
        print(f"Validation error: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"Loaded {len(df)} records from {args.input}")

    # --- Analyse ---
    update = generate_weekly_update(df)

    # --- Render ---
    markdown = render_markdown(update)

    # --- Write output ---
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(markdown, encoding="utf-8")

    print(f"Draft generated: {output_path}")
    print(f"  Highlights: {len(update.highlights)}")
    print(f"  Risks: {len(update.risks)}")
    print(f"  Next steps: {len(update.next_steps)}")


if __name__ == "__main__":
    main()
